-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#5988a6'
local Color12 = '#093c43'
local Color7 = '#16a3b6'
local Color4 = '#d5971a'
local Color13 = '#3f3638'
local Color14 = '#0c4264'
local Color3 = '#e4b781'
local Color10 = '#1679b6'
local Color2 = '#df769b'
local Color9 = '#e3541c'
local Color15 = '#4d6c80'
local Color17 = '#09334e'
local Color8 = '#49ace9'
local Color16 = '#9fb6c6'
local Color6 = '#7060eb'
local Color5 = '#49e9a6'
local Color1 = '#becfda'
local Color11 = '#07273b'

highlight('Comment', nil, Color0, nil)
highlight('TSCharacter', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Conditional', nil, Color2, nil)
highlight('Repeat', nil, Color2, nil)
highlight('Identifier', nil, Color3, nil)
highlight('Constant', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Number', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Error', nil, Color9, nil)
highlight('Comment', nil, nil, 'italic')
highlight('Keyword', nil, nil, 'bold')
highlight('Operator', nil, nil, 'bold')
highlight('Conditional', nil, nil, 'bold')
highlight('Repeat', nil, nil, 'bold')
highlight('StatusLine', Color10, Color11, nil)
highlight('WildMenu', Color11, Color1, nil)
highlight('Pmenu', Color11, Color1, nil)
highlight('PmenuSel', Color1, Color11, nil)
highlight('PmenuThumb', Color11, Color1, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color11, Color1, nil)
highlight('Visual', Color14, nil, nil)
highlight('CursorLine', Color14, nil, nil)
highlight('ColorColumn', Color14, nil, nil)
highlight('SignColumn', Color11, nil, nil)
highlight('LineNr', nil, Color15, nil)
highlight('TabLine', Color17, Color16, nil)
highlight('TabLineSel', Color8, Color11, nil)
highlight('TabLineFill', Color17, Color16, nil)
highlight('TSPunctDelimiter', nil, Color1, nil)

link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSPunctBracket', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TSLabel', 'Type')
link('TSFloat', 'Number')
link('Macro', 'Function')
link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('Repeat', 'Conditional')
link('Operator', 'Keyword')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('TSString', 'String')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Folded', 'Comment')
link('TSOperator', 'Operator')
link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSField', 'Constant')
link('TSNamespace', 'TSType')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSParameter', 'Constant')
link('TSType', 'Type')
link('TSTag', 'MyTag')
link('TSFuncMacro', 'Macro')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSKeyword', 'Keyword')
