-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color16 = '#d2ecf0'
local Color9 = '#ff530f'
local Color18 = '#71838e'
local Color6 = '#5842ff'
local Color0 = '#8ca6a6'
local Color7 = '#0095a8'
local Color15 = '#ecd9d5'
local Color5 = '#00b368'
local Color10 = '#caedf2'
local Color12 = '#005661'
local Color13 = '#f4f6f6'
local Color14 = '#c9ead1'
local Color17 = '#a0abac'
local Color2 = '#ff5792'
local Color11 = '#0099ad'
local Color1 = '#004d57'
local Color3 = '#fa8900'
local Color4 = '#a88c00'
local Color8 = '#0094f0'

highlight('Comment', nil, Color0, nil)
highlight('TSCharacter', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Conditional', nil, Color2, nil)
highlight('Repeat', nil, Color2, nil)
highlight('Identifier', nil, Color3, nil)
highlight('Constant', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Number', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Error', nil, Color9, nil)
highlight('Comment', nil, nil, 'italic')
highlight('Keyword', nil, nil, 'bold')
highlight('Operator', nil, nil, 'bold')
highlight('Conditional', nil, nil, 'bold')
highlight('Repeat', nil, nil, 'bold')
highlight('StatusLine', Color11, Color10, nil)
highlight('WildMenu', Color13, Color12, nil)
highlight('Pmenu', Color13, Color12, nil)
highlight('PmenuSel', Color12, Color13, nil)
highlight('PmenuThumb', Color13, Color12, nil)
highlight('DiffAdd', Color14, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color13, Color12, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color10, Color18, nil)
highlight('TabLineSel', Color11, Color13, nil)
highlight('TabLineFill', Color10, Color18, nil)
highlight('TSPunctDelimiter', nil, Color12, nil)

link('TSFuncMacro', 'Macro')
link('Repeat', 'Conditional')
link('Folded', 'Comment')
link('TSFloat', 'Number')
link('TSOperator', 'Operator')
link('Macro', 'Function')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSField', 'Constant')
link('TSParameter', 'Constant')
link('Whitespace', 'Comment')
link('Operator', 'Keyword')
link('TSProperty', 'TSField')
link('CursorLineNr', 'Identifier')
link('TSString', 'String')
link('NonText', 'Comment')
link('TSFunction', 'Function')
link('TSRepeat', 'Repeat')
link('TSTag', 'MyTag')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSConditional', 'Conditional')
link('TSNamespace', 'TSType')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('TelescopeNormal', 'Normal')
