-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color9 = '#ff530f'
local Color13 = '#c8e6d2'
local Color3 = '#fa8900'
local Color14 = '#ead5d7'
local Color15 = '#d5d1f1'
local Color10 = '#7060eb'
local Color5 = '#00b368'
local Color11 = '#e2dff6'
local Color12 = '#f2f1f8'
local Color4 = '#a88c00'
local Color2 = '#ff5792'
local Color1 = '#0c006b'
local Color7 = '#0095a8'
local Color8 = '#0094f0'
local Color0 = '#9995b7'
local Color16 = '#9d9ab1'
local Color6 = '#5842ff'
local Color17 = '#75718e'

highlight('Comment', nil, Color0, nil)
highlight('TSCharacter', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Conditional', nil, Color2, nil)
highlight('Repeat', nil, Color2, nil)
highlight('Identifier', nil, Color3, nil)
highlight('Constant', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Number', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Error', nil, Color9, nil)
highlight('Comment', nil, nil, 'italic')
highlight('Keyword', nil, nil, 'bold')
highlight('Operator', nil, nil, 'bold')
highlight('Conditional', nil, nil, 'bold')
highlight('Repeat', nil, nil, 'bold')
highlight('StatusLine', Color10, Color11, nil)
highlight('WildMenu', Color12, Color1, nil)
highlight('Pmenu', Color12, Color1, nil)
highlight('PmenuSel', Color1, Color12, nil)
highlight('PmenuThumb', Color12, Color1, nil)
highlight('DiffAdd', Color13, nil, nil)
highlight('DiffDelete', Color14, nil, nil)
highlight('Normal', Color12, Color1, nil)
highlight('Visual', Color15, nil, nil)
highlight('CursorLine', Color15, nil, nil)
highlight('ColorColumn', Color15, nil, nil)
highlight('SignColumn', Color12, nil, nil)
highlight('LineNr', nil, Color16, nil)
highlight('TabLine', Color11, Color17, nil)
highlight('TabLineSel', Color10, Color12, nil)
highlight('TabLineFill', Color11, Color17, nil)
highlight('TSPunctDelimiter', nil, Color1, nil)

link('TSLabel', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('CursorLineNr', 'Identifier')
link('TSRepeat', 'Repeat')
link('Conditional', 'Operator')
link('TSFuncMacro', 'Macro')
link('TSKeyword', 'Keyword')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
link('Macro', 'Function')
link('Operator', 'Keyword')
link('TSParameter', 'Constant')
link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Repeat', 'Conditional')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('TSNamespace', 'TSType')
link('Folded', 'Comment')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('TSFunction', 'Function')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
